language: java

addons:
  sonarcloud:
    organization: "svenpeldszus-github"

script:
 # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
