language: java
dist: bionic
services: mongodb
cache:
  directories:
  - $HOME/.m2
addons:
  sonarcloud:
    organization: "svenpeldszus-github"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=metric.correlation.analysis.core:metric.correlation.analysis.tycho-parent 
